In [8]:
import numpy as np # 导入numpy库

# 创建ndarray
a = np.array([1,2,1])
print(a)
# 操作ndarray
print(a.size) # 查看元素个数
print(a.ndim) # 查看维数

[1 2 1]
3
1


In [37]:
# 专题1：创建ndarray
# 1. 零ndarray
b = np.zeros(100)
print(b)

c = np.zeros((2,3),dtype = 'int64')
print(c)
# 2. 单位ndarry
one_a = np.ones((3,2),dtype='int64')
print(one_a)

# 3. 随机ndarry
rand_a = np.random.rand(4,3) # 4行3列的连续均匀分布[0,1)
print(rand_a)

randint_a = np.random.randint([1,3],[9,10],size=(2,2)) # 5行3列的离散均匀分布[1,10)
print(randint_a)



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]
[[0 0 0]
 [0 0 0]]
[[1 1]
 [1 1]
 [1 1]]
[[0.46241322 0.57428957 0.29128704]
 [0.05971546 0.94458433 0.29752747]
 [0.61279118 0.70156513 0.29074436]
 [0.62492375 0.66622209 0.24629856]]
[[2 4]
 [7 7]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
